CRUD Hibernate
Gar24s8/CRUD pull request #2
Opened 2023-06-23 09:47 UTC by Gar24s8

2023-06-28 10:03 UTC, okhelen requested changes

2023-06-28 10:03 UTC, okhelen commented on pom.xml
> +    <artifactId>CRUD2-Hibernate</artifactId>
artifactId принадлежит проекту и не должен меняться с каждым релизом без уважительных причин. Использование ORM уважительной причиной не является. Вообще он должен отражать бизнес-смысл проекта. Например, ИС ПЗ)

2023-06-28 10:03 UTC, okhelen commented on src/main/java/Demo.java
> +        Employee employee1 = new Employee("Elena", "boss", 500000);
одобряю зп, но класс Demo является сервисом, почему он не лежит в пакете services?

2023-06-28 10:03 UTC, okhelen commented on src/main/java/dao/DAOImpl.java
> +        Office findOffice = null;
Для имен переменных лучше использовать существительные (foundOffice / office) или прилагательные/причастия (isArchived e.g.), глаголы лучше оставить для методов

2023-06-28 10:03 UTC, okhelen commented on src/main/java/models/Tasks.java
> +public class Tasks {
При нейминге сущностей следует придерживаться одной системы. Employee, Office, TaskS - найди лишнее

2023-06-28 10:03 UTC, okhelen commented on src/main/java/models/Tasks.java
> +    @ManyToMany(cascade = CascadeType.ALL)
С использованием CascadeType нужно быть аккуратным, особенно при  удалении. Помимо того что удалять сотрудника при удалении задачи странно с точки зрения бизнес-логики, ты рискуешь нарваться на ошибки (см. скрин), либо удалить лишнее т.к. связь  MM будет цеплять больше задачи и сотрудников, чем ты предполагаешь.
https://thorben-janssen.com/hibernate-tips-the-best-way-to-remove-entities-from-a-many-to-many-association/
![изображение](https://github.com/Gar24s8/CRUD2/assets/34005570/0b7b3d50-673e-4f5e-870a-e26248b4a2ac)

2023-06-28 10:03 UTC, okhelen commented on src/main/java/services/AppService.java
> +public class AppService {
Название AppService несёт также мало смысла как и Service. Что этот сервис делает? Зачем он нужен? В рамках твоего приложения он отвечает за  CRUD  операции. В более реалистичных условиях в этом сервисе помимо вызова дао проверялись бы права на выполнение операций, обрабатывались выходные данные, валидировались входные и т.д. С учетом уже реализованной логики, было бы логично перенести сюда печать результата из дао т.к. дао отвечает ТОЛЬКО за связь с бд

2023-06-28 10:11 UTC, Gar24s8 commented on src/main/java/Demo.java
> +        Employee employee1 = new Employee("Elena", "boss", 500000);
Исправлено

2023-06-28 10:12 UTC, Gar24s8 commented on src/main/java/models/Tasks.java
> +public class Tasks {
Исправлено

2023-06-28 10:21 UTC, Gar24s8 commented on pom.xml
> +    <artifactId>CRUD2-Hibernate</artifactId>
Исправил, изначально начал как отдельный проект, поэтому указал отличные от предыдущего groupid, artifactid, впоследствии забыл исправить

2023-06-28 10:24 UTC, Gar24s8 commented on src/main/java/dao/DAOImpl.java
> +        Office findOffice = null;
Исправлено

2023-06-28 10:27 UTC, Gar24s8 commented on src/main/java/services/AppService.java
> +public class AppService {
Исправлено

2023-07-04 07:10 UTC, Gar24s8 commented on src/main/java/models/Tasks.java
> +    @ManyToMany(cascade = CascadeType.ALL)
Исправлено

2023-07-06 08:43 UTC, merged