Feature/crud4 unit tests
Gar24s8/CRUD pull request #4
Opened 2023-11-15 13:56 UTC by Gar24s8

2023-11-15 14:37 UTC, okhelen requested changes

2023-11-15 14:37 UTC, okhelen commented on CRUD2-Hibernate/src/main/java/servlets/employee/DeleteEmployeeServlet.java
> +    static final String ERROR_PAGE = "/employee/error.jsp";
Ты используешь ERROR_PAGE сразу в нескольких классах, почему бы не сделать её публичной в main или индексе и переиспользовать?

2023-11-15 14:37 UTC, okhelen commented on CRUD2-Hibernate/src/test/java/servlets/employee/IndexEmployeeServletTest.java
> +    public void doGet_shouldPassed_whenEmployeesFound() throws ServletException, IOException {
shouldPassed описывает поведение теста, а не тестируемого кода

2023-11-15 14:37 UTC, okhelen commented on CRUD2-Hibernate/src/test/java/servlets/employee/IndexEmployeeServletTest.java
> +        verify(service).findAllEmployees();
Для читабельности лучше располагать проверки в порядке вызова методов в коде тестируемого метода. Сначала ищешь сотрудников, потом сохраняешь

2023-11-15 14:37 UTC, okhelen commented on CRUD2-Hibernate/src/test/java/servlets/employee/EditEmployeeServletTest.java
> +    public void doPost_shouldShowError_whenNotUpdated() throws ServletException, IOException {
Тест проходит, потому что вызываемый метод падает на ошибке, а не потому, что update возвращает false. Ошибка

2023-11-15 14:37 UTC, okhelen commented on CRUD2-Hibernate/src/test/java/servlets/employee/CreateEmployeeServletTest.java
> +    public void doPost_shouldShowError_whenNotUpdated() throws ServletException, IOException {
Тест проходит, потому что вызываемый метод падает на ошибке, а не потому, что create возвращает false. Ошибка такая же как с update, проверяй

2023-11-15 14:54 UTC, Gar24s8 commented on CRUD2-Hibernate/src/main/java/servlets/employee/DeleteEmployeeServlet.java
> +    static final String ERROR_PAGE = "/employee/error.jsp";
Исправлено

2023-11-15 14:54 UTC, Gar24s8 commented on CRUD2-Hibernate/src/test/java/servlets/employee/IndexEmployeeServletTest.java
> +        verify(service).findAllEmployees();
Исправлено

2023-11-15 14:56 UTC, Gar24s8 commented on CRUD2-Hibernate/src/test/java/servlets/employee/IndexEmployeeServletTest.java
> +    public void doGet_shouldPassed_whenEmployeesFound() throws ServletException, IOException {
Исправлено

2023-11-17 09:59 UTC, Gar24s8 commented on CRUD2-Hibernate/src/test/java/servlets/employee/CreateEmployeeServletTest.java
> +    public void doPost_shouldShowError_whenNotUpdated() throws ServletException, IOException {
Исправлено

2023-11-17 09:59 UTC, Gar24s8 commented on CRUD2-Hibernate/src/test/java/servlets/employee/EditEmployeeServletTest.java
> +    public void doPost_shouldShowError_whenNotUpdated() throws ServletException, IOException {
Исправлено

2023-11-17 10:38 UTC, okhelen approved these changes

2023-11-17 10:38 UTC, merged